---
- name: Check for existing swapfile
  stat: path=/swapfile
  register: swapfile

- name: Stop swapping
  command: swapoff /swapfile
  when: swapfile.stat.exists == true

- name: Remove current swapfile
  file: path=/swapfile state=absent

- name: Write swapfile
  command: fallocate -l 1GB /swapfile creates=/swapfile
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  file: path=/swapfile mode=600
  when: swapfile_size != false

- name: Create swapfile
  command: mkswap /swapfile
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  command: swapon /swapfile
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="/swapfile   none    swap    sw    0   0" state=present
  when: swapfile_size != false

- name: Configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  notify: Reload sysctl
  when: swapfile_swappiness != false

- name: Configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  notify: Reload sysctl
  when: swapfile_vfs_cache_pressure != false
